# Generated by Django 5.2.7 on 2025-10-31 08:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Содержимое'),
        ),
    ]
