# Generated by Django 5.2.7 on 2025-12-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Описание страницы для поисковых систем (до 160 символов)', max_length=500, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (до 60 символов)', max_length=255, verbose_name='Meta Title'),
        ),
    ]
