# Generated by Django 5.2.7 on 2025-11-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authcode'),
        ('core', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_form',
            field=models.CharField(blank=True, max_length=50, verbose_name='ИП или ООО'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_data',
            field=models.TextField(blank=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='product_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Позиция товара'),
        ),
    ]
