# Generated by Django 5.2.7 on 2025-12-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_position',
        ),
    ]
